(WIP) Add MimeTypeMatcher but got cannot borrow compile error
```
error[E0502]: cannot borrow `self.lexer` as immutable because it is also borrowed as mutable
  --> src/mime_type_matcher.rs:44:16
   |
44 |         while !self.lexer.eof() {
   |                ^^^^^^^^^^^^^^^^ immutable borrow occurs here
...
47 |                     if let Some(LexerToken::Token(token)) = self.lexer.token() {
   |                                                             ------------------ mutable borrow occurs here
...
63 |                         let main_type = cur_main_type.take().unwrap();
   |                                         -------------------- mutable borrow later used here
```